### ISSUE TITLE
Issue moving data from a dataframe to bigquery.

### ISSUE THREAD

**Issue by allenwm** [augustin-barillec/google-pandas-load#1]
First, thank you for creating this library. I have been using it for part of our marketing data pipeline  cloud functions and it has worked wonderfully except for one thing. I cannot seem to get it to move data from a dataframe to a bigquery table. 

It will create the table and schema correctly but the data is not inserted. 

![image](https://user-images.githubusercontent.com/41085657/82165199-fc970d80-9868-11ea-83e3-26727870b703.png)

The logs do not indicate that there is any kind of error. 

![image](https://user-images.githubusercontent.com/41085657/82165268-42ec6c80-9869-11ea-85a7-63c30a4814f9.png)

Alas there is no data.

![image](https://user-images.githubusercontent.com/41085657/82165588-7d0a3e00-986a-11ea-803e-85d81793f424.png)

I have checked the dataframes and they do contain data. When I send them as CSVs to cloud storage instead of BQ, they come out perfect.  

There is a minimum age requirement for files in data transfer service (files must be 1 hour old before they will be eligible for consumption by BQ). Perhaps this limitation is stifling the transfer? Please help!

**Comment by augustin-barillec** [comment]
Hello, 
I just saw your message. 

To load data from gs to bq, my code is using the following function: 

    def _gs_to_bq_job(self, gs_to_bq_config):
        config = gs_to_bq_config
        job_config = bigquery.job.LoadJobConfig()
        job_config.field_delimiter = self._separator
        job_config.schema = config.schema
        job_config.skip_leading_rows = 1
        job_config.write_disposition = config.write_disposition
        source_uris = self.list_blob_uris(config.data_name)
        destination = self.dataset_ref.table(
            table_id=config.data_name)
        job = self.bq_client.load_table_from_uri(
            source_uris=source_uris,
            destination=destination,
            job_config=job_config)
        return job 

Can you try to use directly bq_client.load_table_from_uri with different 
parameters to solve the problem ?
