### ISSUE TITLE
Can I query from BQ and not use GS?

### ISSUE THREAD

**Issue by ciro-tc** [augustin-barillec/google-pandas-load#2]
I want to query from BQ and load the results to a dataframe, but do not want to use the Cloud Storage to upload the data.
Is it possible?

Something like:
from google_pandas_load import LoaderQuickSetup

```
gpl = LoaderQuickSetup(
    project_id='pi'
)

df = gpl.load(
    source='query',
    destination='dataframe',
    query='SELECT a,b,c FROM table'
)
```

**Comment by augustin-barillec** [comment]
No it is impossible. You can use this to do what you want: google.cloud.bigquery.job.QueryJob.to_dataframe()
